name: meme_app
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  dartz: ^0.10.1
  mockito: ^5.4.2
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.0
  dio: ^5.2.1+1
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  bloc_test: ^9.1.3
  get_it: ^7.6.0
  card_swiper: ^3.0.1
  http: ^1.1.0

  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  build_runner: ^2.4.6
  freezed: ^2.3.2
  json_serializable: ^6.6.1
  very_good_analysis: ^3.1.0

  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true

  
scripts: 
  build: flutter pub run build_runner build --delete-conflicting-outputs
  
  
  